#!/bin/bash

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

mkdir -p $HERE/bin
wget -q -O bin/structor http://redismodules.s3.amazonaws.com/lab/13-structor/structor
STRUCTOR_LATEST_TAG=v2.2.0
$HERE/bin/structor \
	-o itamarhaber \
	-r redisbloom \
	-d https://gist.githubusercontent.com/itamarhaber/5124fc446d0fec2cfff914c237796cbf/raw/66aeb7a6c11f3079015489fb6cd825768d64c6b2/docs.Dockerfile \
	--menu.js-url="https://gist.githubusercontent.com/itamarhaber/5124fc446d0fec2cfff914c237796cbf/raw/c4d7014a37bed971312363ee53f0aafd053c84c7/versions-menu.js.gotmpl" \
	--exp-branch=master \
	--debug \
	-w /w/lab/mkdocs/01-structor/tmp