version: 2
jobs:
  deploy_docs:
    docker:
      - image: 'debian:buster'
    steps:
      - run:
          name: Setup executor
          command: |
            apt-get -qq update
            apt-get -q install -y git openssh-client curl ca-certificates make tar gzip wget
            bash <(curl -fsSL https://get.docker.com)
      - checkout
      - setup_remote_docker
      - run:
          name: Build docs
          command: ./mkdocs

workflows:
  version: 2
  docs_website:
    jobs:
      - deploy_docs:
          filters:
            tags:
              only: /.*/
